CREATE TABLE `sprints` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL DEFAULT '새 스프린트' COMMENT '스프린트 이름' COLLATE 'utf8mb4_general_ci',
	`description` VARCHAR(255) NULL DEFAULT NULL COMMENT '스프린트 설명' COLLATE 'utf8mb4_general_ci',
	`cycle` INT(10) NOT NULL DEFAULT '0' COMMENT '반복 주기 (사용자지정 : 0)',
	`begin_date` TIMESTAMP NULL DEFAULT NULL COMMENT '스프린트 시작일',
	`end_date` TIMESTAMP NULL DEFAULT NULL COMMENT '스프린트 종료일',
	`updated_at` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP' ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
	`created_at` TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT '생성일',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=2
;
